id = "greycat"
name = "GreyCat"
version = "0.1.0"
schema_version = 1
authors = ["Maxime Tricoire <maxime.tricoire@datathings.com>"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
rev = "09515649fcaf1cab349b4452b06a1dd727f38084"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
