id = "greycat"
name = "GreyCat"
version = "0.1.0"
schema_version = 1
authors = ["maxleiko", "datathings"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
commit = "8427de2152f682d30d230fcfb6d9915db1be4a7b"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
