id = "greycat"
name = "GreyCat"
version = "0.1.0"
schema_version = 1
authors = ["maxleiko", "datathings"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
commit = "f2484b37211d4608c7885359a0a5e3736252403e"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
