id = "greycat"
name = "GreyCat"
version = "0.1.0"
schema_version = 1
authors = ["Maxime Tricoire <maxime.tricoire@datathings.com>"]
description = "GreyCat support."
repository = "https://github.com/maxleiko/zed-greycat-extension"

[grammars.greycat]
repository = "https://github.com/maxleiko/tree-sitter-greycat"
commit = "0a8499e876fd0e4a051a5564bb12ea84a1bb1d2a"

[language_servers.greycat]
name = "GreyCat Language Server"
languages = ["GreyCat"]
